# verify.yml
- name: Verify collections usage
  hosts: localhost
  gather_facts: false

  vars:
    rand_len: 12

  tasks:
    - name: Generate a random string via lookup
      set_fact:
        my_random: "{{ lookup('community.general.random_string', 'length=' ~ rand_len) }}"

    - name: Show it
      debug:
        msg: "random = {{ my_random }}"