---
- name: Verify PAH collections
  hosts: all
  gather_facts: false
  collections:
    - community.general
    - ansible.posix
  tasks:
    - name: Show collection paths
      ansible.builtin.debug:
      var: ansible_env.ANSIBLE_COLLECTIONS_PATHS

    - name: ansible-doc in EE
      ansible.builtin.command: ansible-doc -t module community.general.random_string
      register: doc
      changed_when: false

    - debug: var=doc.stdout

    - name: Generate a random string (community.general)
      community.general.random_string:
        length: 12
      register: rnd

    - name: Show random string
      ansible.builtin.debug:
        var: rnd.result

    - name: Read root fs type (ansible.posix)
      ansible.posix.find_mounts:
        paths: ['/']
      register: mounts

    - name: Show fs type
      ansible.builtin.debug:
        msg: "Root FS type is {{ mounts.mounts[0].fstype }}"