---
- name: Verify PAH collections
  hosts: all
  gather_facts: false
  collections:
    - community.general
    - ansible.posix
  tasks:
    - name: Generate a random string (community.general)
      community.general.random_string:
        length: 12
      register: rnd

    - name: Show random string
      ansible.builtin.debug:
        var: rnd.result

    - name: Read root fs type (ansible.posix)
      ansible.posix.find_mounts:
        paths: ['/']
      register: mounts

    - name: Show fs type
      ansible.builtin.debug:
        msg: "Root FS type is {{ mounts.mounts[0].fstype }}"